easy_admin:
    site_name: 'Administration <em style="font-size: 80%">by EasyAdmin</em>'
    user:
        display_name: true
        display_avatar: true
    formats:
        datetime: 'd/m/Y a H:i'