easy_admin:
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        menu:
            - { label: 'Inventaire' }
            - { entity: 'Equipment', label: 'Equipements', icon: 'toolbox' }
            - { entity: 'Discipline', label: 'Disciplines', icon: 'book' }
            - { entity: 'Room', label: 'Salles', icon: 'building' }
            - { label: 'Les emprunts' }
            - { entity: 'Borrow', label: 'Emprunts', icon: 'book-reader' }
            - { label: 'Les utilisateurs' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }
  