easy_admin:
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        menu:
            - { label: 'Equipements' }
            - { entity: 'Equipment', label: 'Equipements', icon: 'book' }
            - { label: 'Utilisateurs' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }
  